### ISSUE TITLE
"System.ExecutionEngineException occured in Unknown Module" when opening a non-capture audio device

### ISSUE THREAD

**Issue by JamDoggie** [flibitijibibo/SDL2-CS#215] opened 2021-02-17 01:43 UTC
I'm using SDL2-CS Compiled myself from the source in 64 bit. The program i'm making is using 64 bit Avalonia (though i don't think this should have anything to do with the issue) with .net core. I'm trying to make a simple program that takes my microphone input and outputs it back to me. When I run the program, everything runs fine for a while but eventually ends up with this exception. 
![image](https://user-images.githubusercontent.com/17690526/108143712-403bd380-7096-11eb-9fc6-7bc044bbf20f.png)
I understand this is related to the heap being corrupted, which is already a red flag that it's not my code since i'm not doing anything *that* weird. Here's my code. I'm using the FNA classes for microphone directly copy and pasted(as well as enums, what i needed from the FNAPlatform, SDL_FNAPlatform, ect.) because before using my own implementation was giving this error and so i wanted to use code that i knew was(or atleast i'm pretty sure is) working. The thing is, from my testing the microphone part of it is fine and causes no issues, works perfectly as expected. It's only when i open an audio playback device when things start getting funky. 

Here's my code:
```using Avalonia;
using Avalonia.Controls;
using Occlusion.Networking;
using Occlusion.Views;
using OpusDotNet;
using System;
using System.Collections.Generic;
using System.Text;
using System.Timers;

using SDL2;
using System.Runtime.InteropServices;
using System.IO;
using Occlusion.Library;
using static SDL2.SDL;
using Avalonia.Threading;

namespace Occlusion.ViewModels
{
    public class MainWindowViewModel : ViewModelBase
    {
        public Window View { get; set; }

        public LocalClient Client { get; set; }

        private byte[] buffer;

        private MemoryStream stream;

        private Microphone mic = Microphone.Default;

        private uint playbackId = 0;

        private DispatcherTimer timer = new DispatcherTimer();

        public void SendMessageClicked()
        {
            ChatMessagePacket messagePacket = new ChatMessagePacket();
            messagePacket.Message = View.FindControl<TextBox>("InputBox").Text;
            messagePacket.Username = "Guest";
            messagePacket.Send(Client);
            View.FindControl<TextBox>("InputBox").Text = "";

            Console.WriteLine("sent message");
        }

        public void StartMic()
        {
            Console.WriteLine("Starting sound system");

           

            mic.BufferDuration = TimeSpan.FromMilliseconds(500);
            buffer = new byte[mic.GetSampleSizeInBytes(mic.BufferDuration)];

            mic.BufferReady += handleBufferReady;

            mic.Start();

            var defaultOutputDevice = SDL_GetAudioDeviceName(1, 0);
            
            Console.WriteLine($"Default output device: {defaultOutputDevice}");

            // Check to make sure we have audio output devices even connected first.
            if (SDL_GetNumAudioDevices(0) > 0)
            {
                // Set up debug playback device
                SDL_AudioSpec wanted_settings = new SDL_AudioSpec();
                SDL_AudioSpec final_settings;
                wanted_settings.freq = Microphone.SAMPLERATE;
                wanted_settings.format = AUDIO_S16;
                wanted_settings.channels = 1;
                wanted_settings.freq = 4096;
                wanted_settings.callback = audioOutputCallback;

                // This is our main play back device we will use to play back microphones.
                playbackId = SDL_OpenAudioDevice(defaultOutputDevice, 0, ref wanted_settings, out final_settings, 0);

                SDL_PauseAudioDevice(playbackId, 0);
            }

            timer.Interval = TimeSpan.FromMilliseconds(1);
            timer.Tick += new EventHandler(timer_Tick);
            timer.Start();
        }

        private void handleBufferReady(object sender, EventArgs e)
        {
            mic.GetData(buffer);

            foreach(byte b in buffer)
            {
                //Console.Write(b + " ");
            }

            //Console.Write("\n");

            GCHandle handle1 = GCHandle.Alloc(buffer); // Get the handle for the microphone buffer we made
            IntPtr pointer = (IntPtr)handle1;          // so that we can get the IntPtr of the buffer

            handle1.Free();                            // (We can then immediately free the handle because it's not needed anymore, we just needed the IntPtr)


            /*int code = SDL_QueueAudio(playbackId, pointer, (uint)buffer.Length);
            if (code < 0)
            {
                Console.WriteLine($"SDL Error code {code}: {SDL_GetError()}");
            }*/
        }

        private void audioOutputCallback(IntPtr userdata, IntPtr stream, int len)
        {
            Console.WriteLine("audio output callback");
        }


        void timer_Tick(object sender, EventArgs e)
        {
            if (Microphone.micList != null)
            {
                for (int i = 0; i < Microphone.micList.Count; i += 1)
                {
                    Microphone.micList[i].CheckBuffer();
                }
            }
        }
    }
}
```

Some notes: 
- 'StartMic()' is essentially the initialize method here. It's run from a UI button press.

- Commenting out all the callback related stuff including the timer for the playback device still causes the error eventually. The only thing that stops this error from happening is commenting out the "SDL_PauseAudioDevice(playbackId, 0);" line, which just is meant to unpause the device's playback, leading me to believe this is what's causing the issue.

Also something i'd like to note: The code from FNA actually didn't work properly at first. When i pass null as the device string when starting a capture device, there's an assert that stops the program from even running; This meant i had to make it get the default device name manually and pass it instead of null for the default Microphone. Does this mean i'm somehow using the wrong version of the wrapper or something? Because the expected behavior(as also seen in both the FNA codebase and SDL docs) is that passing null should automatically use the default device, not throw an exception.

EDIT: Also sorry i apologize for leaving in the "SendMessageClicked" method, this is completely unrelated code to the issue and is a left over of a networking test i was doing. Everything else in the codeblock though is fair game.

**Comment by flibitijibibo** [comment] 2021-02-17 03:24
>I understand this is related to the heap being corrupted, which is already a red flag that it's not my code since i'm not doing anything that weird

>because before using my own implementation was giving this error and so i wanted to use code that i knew was(or atleast i'm pretty sure is) working

Not a good way to start a report, especially when you have this block:

```
handle1.Free(); // (We can then immediately free the handle because it's not needed anymore, we just needed the IntPtr)
```
Not true! You need that pin for the duration that the pointer is used, so it needs to be freed after SDL_QueueAudio. You also appear to be using an audio callback at the same time as SDL_QueueAudio when you can only have one or the other; in this case you probably want `wanted_settings.callback = null` or something to that effect. It could _also_ be that the callback delegate is getting collected, which is also a common cause of that exception:

https://stackoverflow.com/questions/6193711/call-has-been-made-on-garbage-collected-delegate-in-c

You can verify that the issue isn't on our end by replacing all the custom code in this sample with FNA's DynamicSoundEffectInstance.

**Comment by JamDoggie** [comment] 2021-02-17 03:58
```
handle1.Free(); // (We can then immediately free the handle because it's not needed anymore, we just needed the IntPtr)
Not true! You need that pin for the duration that the pointer is used, so it needs to be freed after SDL_QueueAudio.
```
OH GOD ok then, yeah i misread that for sure. Guess this is why we leave comments, so people can point out exactly why you did something wrong lol!

> You also appear to be using an audio callback at the same time as SDL_QueueAudio when you can only have one or the other

Yeah this is a byproduct of me just messing around with stuff. Before i was queueing it and it said it could only be used with a callback and i just forgot to remove it from the codeblock i sent(i had commented the queue code before and the behavior was the same)

> It could also be that the callback delegate is getting collected, which is also a common cause of that exception:

What would i do in this case, is there a way to keep the garbage collector from touching it?


If none of this changes anything after tinkering around i will use DynamicSoundEffectInstance from FNA and get back to you. This could very well just be me being a dummy.

**Comment by flibitijibibo** [comment] 2021-02-17 04:04
Yeah, the SO link covers it pretty well - it's easily the worst part of C# interop, for some reason you have to store a copy of the delegate in a persistent variable (usually just a class variable or even a static variable), _then_ pass it to the P/Invoke functions.

**Comment by JamDoggie** [comment] 2021-02-17 04:26
Ok another problem, I've just realized in the QueueAudio code I was also getting the size of the buffer wrong. How would I correctly get the size of the buffer? C# isn't really made for this kind of memory management and doing this kind of stuff seems very janky so I'm confused.

**Comment by flibitijibibo** [comment] 2021-02-17 04:35
It may actually be easier to copy testcapture.c into C# form, then work it into whatever you need:

https://github.com/libsdl-org/SDL/blob/main/test/testaudiocapture.c

**Comment by JamDoggie** [comment] 2021-02-17 21:40
You know what, after doing quite a bit of testing, it is absolutely the delegate is getting garbage collected. I also get an error message saying just that if i force the console to open and run it without debugging. Queuing audio instead of using a callback completely eliminates this issue. So in the end, i guess it's up to you. You *could* view it as something that could be fixed within the wrapper, or it could be viewed as something that's not really the wrapper's fault either.

**Comment by flibitijibibo** [comment] 2021-02-17 22:31
If you go to that struct member decalaration, change it to an IntPtr, and assign it with Marshal.GetFunctionPointerForDelegate, does that fix it? If so I suppose we could deal with it that way, but I dunno how many people depend on how it is right now.

**Comment by JamDoggie** [comment] 2021-02-18 21:54
Weirdly it still gets garbage collected... am I doing something wrong? Here's what I did

```private IntPtr outputCallback;``` in the class

```outputCallback = Marshal.GetFunctionPointerForDelegate((SDL_AudioCallback)audioOutputCallback);``` in the constructor

```wanted_settings.callback = (SDL_AudioCallback)Marshal.GetDelegateForFunctionPointer(outputCallback, typeof(SDL_AudioCallback));``` when setting the callback

and finally the callback itself:
```private void audioOutputCallback(IntPtr userdata, IntPtr stream, int len)
        {
            Console.WriteLine("audio output callback");
        }```

**Comment by flibitijibibo** [comment] 2021-02-18 21:58
I meant modifying this field:

https://github.com/flibitijibibo/SDL2-CS/blob/master/src/SDL2.cs#L7511

That way you would get a pointer directly from the function with no delegates in the middle.

**Comment by JamDoggie** [comment] 2021-02-18 22:14
Ah, alright. Assuming I did it right no, it still gets collected. 

Just for reference I:
- changed it from a delegate to an IntPtr in the library, compiled and referenced it in my project
- assigned the callback like this: 
```wanted_settings.callback = Marshal.GetFunctionPointerForDelegate((SDL_AudioCallback)audioOutputCallback);```

**Comment by JamDoggie** [comment] 2021-02-18 22:36
Just in case, this is the exact error message copy pasted from the console 
```Process terminated. A callback was made on a garbage collected delegate of type 'SDL2-CS!SDL2.SDL+SDL_AudioCallback::Invoke'.```

**Comment by flibitijibibo** [comment] 2021-02-18 23:01
Got it... maybe it just wants the AudioSpec variable kept static/global?

**Comment by JamDoggie** [comment] 2021-02-18 23:18
Making both the AudioSpecs public static members of the object still makes it get garbage collected. This is also still with the modification in. I'm really surprised how persistent this garbage collector is..

**Comment by flibitijibibo** [comment] 2021-02-19 01:25
This may be a good time to try Mono and .NET Framework rather than Core - I happen to know that Mono will never hit this, Framework might hit it but people have been using this API for a while, so it surprises me that it's struggling so much with the delegate.

**Comment by flibitijibibo** [comment] 2021-04-19 15:50
Closing as a .NET Core thing - Framework and Mono are fine so this would have to be filed with the .NET Foundation instead.

**Closed by flibitijibibo** 2021-04-19 15:50 UTC
